name: Deploy Main and Beta to GitHub Pages
on:
  push:
    branches:
      - main 
      - beta 
  workflow_dispatch:

permissions:
  contents: write # Required to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment structure
        run: mkdir -p gh-pages-content/beta

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main 
          path: main-content 

      - name: Checkout beta branch
        uses: actions/checkout@v4
        with:
          ref: beta 
          path: beta-content 

      - name: Prepare content
        run: |
          # Copy main content to deployment root (excluding .git)
          rsync -av --exclude='.git/' main-content/ gh-pages-content/
          
          # Copy beta content to beta directory (excluding .git)
          rsync -av --exclude='.git/' beta-content/ gh-pages-content/beta/ 
          
          # Create .nojekyll file to prevent Jekyll processing
          touch gh-pages-content/.nojekyll
          
          # Debug: list content recursively
          echo "Deployment content (recursive):"
          ls -laR gh-pages-content

      - name: Push to gh-pages branch
        run: |
          cd gh-pages-content
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy main and beta to GitHub Pages" 
          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages